import { AppUser, FoodOrder, FoodProduct } from '../types/commerce';

export const initialProducts: FoodProduct[] = [
  {
    id: 'p1',
    name: 'Margherita Pizza',
    description: 'Stone-baked pizza with tomato, mozzarella, and basil.',
    category: 'Pizza',
    price: 14.99,
    imageUrl: 'https://images.unsplash.com/photo-1604382355076-af4b0eb60143?auto=format&fit=crop&w=900&q=80',
    supplierId: 'supplier1',
    supplierName: 'supplier1',
    stock: 24,
    status: 'approved',
  },
  {
    id: 'p2',
    name: 'Cheeseburger Deluxe',
    description: 'Juicy grilled beef, cheddar, caramelized onions, and house sauce.',
    category: 'Burgers',
    price: 12.49,
    imageUrl: 'https://images.unsplash.com/photo-1568901346375-23c9450c58cd?auto=format&fit=crop&w=900&q=80',
    supplierId: 'supplier2',
    supplierName: 'supplier2',
    stock: 30,
    status: 'approved',
  },
  {
    id: 'p3',
    name: 'Salmon Poke Bowl',
    description: 'Fresh salmon, avocado, cucumber, seaweed, and sesame rice.',
    category: 'Bowls',
    price: 15.75,
    imageUrl: 'https://images.unsplash.com/photo-1546069901-ba9599a7e63c?auto=format&fit=crop&w=900&q=80',
    supplierId: 'supplier1',
    supplierName: 'supplier1',
    stock: 18,
    status: 'approved',
  },
  {
    id: 'p4',
    name: 'Pasta Alfredo',
    description: 'Creamy parmesan alfredo pasta with roasted mushrooms.',
    category: 'Pasta',
    price: 13.9,
    imageUrl: 'https://images.unsplash.com/photo-1621996346565-e3dbc646d9a9?auto=format&fit=crop&w=900&q=80',
    supplierId: 'supplier2',
    supplierName: 'supplier2',
    stock: 22,
    status: 'approved',
  },
  {
    id: 'p5',
    name: 'Chicken Tacos',
    description: 'Soft tacos with grilled chicken, pico de gallo, and lime crema.',
    category: 'Mexican',
    price: 11.99,
    imageUrl: 'https://images.unsplash.com/photo-1613514785940-daed07799d9b?auto=format&fit=crop&w=900&q=80',
    supplierId: 'supplier1',
    supplierName: 'supplier1',
    stock: 20,
    status: 'approved',
  },
  {
    id: 'p6',
    name: 'Sushi Set',
    description: 'Assorted sushi platter with salmon, tuna, and shrimp rolls.',
    category: 'Sushi',
    price: 19.99,
    imageUrl: 'https://images.unsplash.com/photo-1579871494447-9811cf80d66c?auto=format&fit=crop&w=900&q=80',
    supplierId: 'supplier2',
    supplierName: 'supplier2',
    stock: 16,
    status: 'approved',
  },
  {
    id: 'p7',
    name: 'Caesar Salad',
    description: 'Crisp romaine, parmesan, croutons, and classic Caesar dressing.',
    category: 'Salads',
    price: 9.5,
    imageUrl: 'https://images.unsplash.com/photo-1512621776951-a57141f2eefd?auto=format&fit=crop&w=900&q=80',
    supplierId: 'supplier1',
    supplierName: 'supplier1',
    stock: 28,
    status: 'approved',
  },
  {
    id: 'p8',
    name: 'Chocolate Brownie',
    description: 'Rich chocolate brownie with sea salt and vanilla cream.',
    category: 'Desserts',
    price: 6.25,
    imageUrl: 'https://images.unsplash.com/photo-1606313564200-e75d5e30476c?auto=format&fit=crop&w=900&q=80',
    supplierId: 'supplier2',
    supplierName: 'supplier2',
    stock: 35,
    status: 'approved',
  },
  {
    id: 'p9',
    name: 'Iced Matcha Latte',
    description: 'Premium matcha with milk and light cane syrup.',
    category: 'Drinks',
    price: 5.99,
    imageUrl: 'https://images.unsplash.com/photo-1515823662972-da6a2e4d3002?auto=format&fit=crop&w=900&q=80',
    supplierId: 'supplier1',
    supplierName: 'supplier1',
    stock: 40,
    status: 'approved',
  },
  {
    id: 'p10',
    name: 'Vegan Buddha Bowl',
    description: 'Quinoa, roasted chickpeas, kale, carrots, and tahini dressing.',
    category: 'Bowls',
    price: 13.25,
    imageUrl: 'https://images.unsplash.com/photo-1511690743698-d9d85f2fbf38?auto=format&fit=crop&w=900&q=80',
    supplierId: 'supplier2',
    supplierName: 'supplier2',
    stock: 19,
    status: 'pending',
  },
];

export const initialUsers: AppUser[] = [
  { id: 'u1', username: 'customer1', email: 'customer1@food.com', role: 'Customer', status: 'active' },
  { id: 'u2', username: 'customer2', email: 'customer2@food.com', role: 'Customer', status: 'active' },
  { id: 'u3', username: 'supplier1', email: 'supplier1@food.com', role: 'Supplier', status: 'active' },
  { id: 'u4', username: 'supplier2', email: 'supplier2@food.com', role: 'Supplier', status: 'active' },
  { id: 'u5', username: 'steward1', email: 'steward1@food.com', role: 'Data Steward', status: 'active' },
  { id: 'u6', username: 'steward2', email: 'steward2@food.com', role: 'Data Steward', status: 'active' },
];

export const initialOrders: FoodOrder[] = [
  {
    id: 'FOOD-1001',
    userSub: 'customer1',
    userName: 'customer1',
    status: 'delivered',
    createdAt: new Date(Date.now() - 1000 * 60 * 60 * 48).toISOString(),
    items: [
      {
        productId: 'p1',
        name: 'Margherita Pizza',
        imageUrl: 'https://images.unsplash.com/photo-1604382355076-af4b0eb60143?auto=format&fit=crop&w=900&q=80',
        price: 14.99,
        quantity: 1,
        subtotal: 14.99,
      },
      {
        productId: 'p8',
        name: 'Chocolate Brownie',
        imageUrl: 'https://images.unsplash.com/photo-1606313564200-e75d5e30476c?auto=format&fit=crop&w=900&q=80',
        price: 6.25,
        quantity: 2,
        subtotal: 12.5,
      },
    ],
    total: 27.49,
  },
  {
    id: 'FOOD-1002',
    userSub: 'customer2',
    userName: 'customer2',
    status: 'processing',
    createdAt: new Date(Date.now() - 1000 * 60 * 60 * 7).toISOString(),
    items: [
      {
        productId: 'p3',
        name: 'Salmon Poke Bowl',
        imageUrl: 'https://images.unsplash.com/photo-1546069901-ba9599a7e63c?auto=format&fit=crop&w=900&q=80',
        price: 15.75,
        quantity: 1,
        subtotal: 15.75,
      },
    ],
    total: 15.75,
  },
];
